### ISSUE TITLE
async cells are sometimes executed out of order

### ISSUE THREAD

**Issue by saraedum** [Kirill888/jupyter-ui-poll#16]
Running all cells in this notebook (with Cell → Run All) executes cells out of order:

![image](https://user-images.githubusercontent.com/373765/136464740-3b1a0d62-5dfb-4cfc-bc8f-ab5aa34357dc.png)

This happened with the latest version of this package and the latest notebook from conda-forge.

I am happy to provide more details if that is helpful.

**Comment by saraedum** [comment]
This is likely because I am on ipykernel 5.5.5.

**Comment by saraedum** [comment]
I don't claim to fully understand what I am doing here but this fixes the issue for me:
```patch
diff --git a/jupyter_ui_poll/_poll.py b/jupyter_ui_poll/_poll.py
index 81fb11e..3f80957 100644
--- a/jupyter_ui_poll/_poll.py
+++ b/jupyter_ui_poll/_poll.py
@@ -89,9 +89,7 @@ class KernelWrapper:
             if kernel._aborting:
                 kernel._send_abort_reply(stream, parent, ident)
             else:
-                rr = kernel.execute_request(stream, ident, parent)
-                if self._kernel_is_async:
-                    await rr
+                await kernel.execute_request(stream, ident, parent)

                 # replicate shell_dispatch behaviour
                 sys.stdout.flush()

```

**Comment by Kirill888** [comment]
Thanks for the report @saraedum , I can't say I have tested async + older ipykernel, it could be that `kernel.execute_request` returns awaitable when operating in async mode, completely disabling that check is not an option though as this would break synchronous case on series 5.* of ipykernel.

Code here can be improved though

https://github.com/Kirill888/jupyter-ui-poll/blob/ce4e3d458299a4b3ea79eddb02b8ad079b8ac8fc/jupyter_ui_poll/_poll.py#L92-L94

Probably most robust is to check whether `rr` is "awaitable", and then await, instead of relying on per-kernel check.
